---
- name: Install Python3 and pip
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Docker Python SDK
  pip:
    name: docker
    executable: pip3 # Explicitly use pip3

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Log in to GitHub Container Registry
  docker_login:
    registry: ghcr.io
    username: "{{ github_username }}"
    password: "{{ github_token }}"

- name: Pull Docker image
  docker_image:
    name: "ghcr.io/{{ github_repo }}:{{ image_tag }}"
    source: pull

- name: Stop and remove existing container
  docker_container:
    name: schema-manager
    state: absent
    force_kill: yes

- name: Run Docker container
  docker_container:
    name: schema-manager
    image: "ghcr.io/{{ github_repo }}:{{ image_tag }}"
    state: started
    restart_policy: unless-stopped
    env:
      DB_HOST: "{{ postgres_host }}"
      DB_PORT: "{{ postgres_port }}"
      DB_NAME: "{{ db_name }}"
      DB_USER: "{{ db_user }}"
      DB_PASSWORD: "{{ db_password }}"
    volumes:
      - "/var/log/schema-manager:/app/logs"
