name: Deploy with Ansible

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag (e.g., v1.0.0)"
        required: true
      db_name:
        description: "PostgreSQL database name"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          # Verify SSH connection
          ssh -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"

      - name: Run Ansible Playbook
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          cd ansible
          ansible-playbook playbook.yml \
            -i inventory.ini \
            -e "github_repo=${{ github.repository }}" \
            -e "image_tag=${{ github.event.inputs.image_tag }}" \
            -e "db_name=${{ github.event.inputs.db_name }}" \
            -e "github_username=${{ github.actor }}" \
            -e "github_token=${{ secrets.GITHUB_TOKEN }}" \
            --private-key ~/.ssh/deploy_key.pem \
            -vvv  # Verbose logging for debugging
